---
title: "plotly"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: journal
---

### Let's look at NYC Restaruant Inspection dataset
```{r, include = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

### Load, clean and filter the dataset
```{r}
data("rest_inspec")
inspec_data = 
  rest_inspec %>%
  janitor::clean_names() %>%
  select(boro, zipcode, street, cuisine_description, grade, score, grade_date) %>%
  drop_na(score)
```

### scatterplot
```{r}
inspec_data %>%
  filter(grade %in% c("A","B","C"), boro == "BRONX",!( cuisine_description == "Not Listed/Not Applicable") ) %>%

  mutate(cuisine_description = fct_reorder(cuisine_description,score)) %>%
  mutate(
    cuisine_description = as.factor(cuisine_description),
    cuisine_description = fct_recode(
      cuisine_description, 
      "Latin" = "Latin (Cuban, Dominican, Puerto Rican, South & Central American)",
      "Juice" = "Juice, Smoothies, Fruit Salads" ,
      "Mixed Buffet" = "Sandwiches/Salads/Mixed Buffet" ,
      "Beverages" = "Bottled beverages, including water, sodas, juices, etc.")) %>%
      
  plot_ly(
    x = ~cuisine_description, y = ~score, 
    color = ~grade , alpha = 0.5,
    type = "scatter", mode = "markers", colors = "viridis"
  ) %>%
  layout(title = "Score of Different Cuisine Type in Bronx")
```
The scatter plot shows the relationship between cuisine type and score in Bronx area.

### boxplot
```{r}
inspec_data %>%
  filter(zipcode == "10030") %>%
  mutate(street = fct_reorder(street, score)) %>%
  mutate(
    street = as.factor(street),
    street = fct_recode(
      street, 
      "WEST 135 STREET" = "W 135TH ST",
      "WEST 135 STREET" = "W 135 STREET",
      "WEST 135 STREET" = "WEST  135 STREET",
      "WEST 139 STREET" = "W 139TH ST",
      "7 AVENUE" = "7TH AVE",
      "ADAM CLAYTON POWELL BLVD" = "ADAM CLAYTON POWELL JR BOULEVARD",
      "ADAM CLAYTON POWELL BLVD" = "ADAM CLAYTON POWELL BOULEVARD",
      "ADAM CLAYTON POWELL BLVD" = "ADAM CLAYTON POWELL JR B",
      "ADAM CLAYTON POWELL BLVD" = "ADAM CLAYTON POWELL JR BLVD",
      "ADAM CLAYTON POWELL BLVD" = "A C POWELL BLVD",
      "FREDERICK DOUGLASS BLVD" = "FREDERICK DOUGLASS BOULEVARD",
      "FREDERICK DOUGLASS BLVD" = "FREDERICK DOUGLAS BOULEVARD",
      "FREDERICK DOUGLASS BLVD" = "FRDERICK DOUGLASS BOULEVARD",
      "FREDERICK DOUGLASS BLVD" = "FEDERICK DOUGLAS BLVD",
      "ST NICHOLAS AVENUE" = "ST NICHOLAS AV"
      
      )) %>%
  plot_ly(x = ~street, y = ~score,
          type = "box", color = ~street,
          colors = "viridis") %>%
  layout(title = "Restaurants' Score by Street where Zipcode is 10030")
```
The boxplot shows the score distribution of restaurants by street in where zip code is 10030.

### histogram
```{r}
inspec_data %>%
  filter(grade %in% c("A", "B", "C"), !(boro == "Missing")) %>%
  mutate(
    boro = as.factor(boro),
    grade = as.factor(grade)
  ) %>% 
  group_by(boro, grade) %>% 
  count(boro, grade) %>% 
  plot_ly(
    x = ~boro, y = ~n, color = ~grade, type = "bar", colors = "viridis"
  ) %>%
  layout(title = "Distribution of Grade by Boro")
```
This histogram shows the distribution of grade in each boro.
